language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rrIvkdBUCKfPPulZ54R6ZO30L7ilouQLLfhv0Emuy70OFmTrIc2UYvefl4HqlQhSiPqVMjgFNYq8/m5ARGOeULIqWdfDpiC1BOHZKzoDvFtXShFWzLM8Bbw2aZk70KpqkX2LSMHzrGQQP1BBk7/HfyfpPVp9oeDX2q0ypS07kTQfKGhD5xvI4EvvVxyFITmyDmVFK3gk9eWUNGpzlOli/qfX0j2AFO2tcepHwfp+U5qkqLj+NGbInz3HGVwxyAtsDEkS+WxW0+o8aApeu0jBTBV7To3jG7gRsGscCA9odPUy6ODyz/hJ43ItqQN3Py+dkqd8ovE4kGLkBsfftHYvnIDD34uMUsEGWvt8GXMSCJEnNkhck6pGigVWAV0L7x/mx5Lzf3jAyhazkBPpMfbd67X6r8ucX86FkU37GovC2GSPdVQenGRmKDaJBjb2SCljbeuwYqezcs+Dm35FF6uVLiJyY3RY8NNj4R/Tqqjp8YM0bspROrQ5S3zhXTExEADdbiZqLWUZvRwnkOomkjEQbAejHhYa7G7mDJA+2dp10AJkkFsKVv+g/E65Me34iCBXaYs9iea+krEnqIOM0U7YU+6HsP4plDtfCdPmGXjpWyW8FfoC7xaNzeMnkSFUa0k7n5pk4FGOoxtHjg6X9sEdf4HOZV2jxMYmMxs73fTSpJw=
  app: crypto-numismatics
  on:
    repo: thomahau/crypto-numismatics
  skip_cleanup: 'true'
env:
  global:
    secure: AYL+WAkbh6UAWQxezul0LGztl7A4qx3nKKgmSWfnsiuC/zjcBhLxFtGLv2qC2FXAEL505yZOyDp0yvY3IXF6qZiv6Wh2HbQ9VOqah/XhTNaCRd3NVr7YgcLYCYk13ynD7ww+fhxnEcRzGw5x8vmT9ylUghJv9vaax1rZPTWswzmHM4cp/YOHyImdvQFnXWHg67BcZZjgmbMVn/Sj/SoRr/vRC2cI4TpetHgHNbANjSMmiCpDHABAA5x0vlsyHAuSx+4alsW7etGJFl07HOhLjdGwJFpWF8vQVpIvYb9HIRmXxC83Zj0uAG8F0YLgt21bs3xn7YNDGm+EhUiW9CBiwmJqAbwbt6BQAz6RvVSvpgwN7EYEQ99Y090v7+29+NjH4nvo7lVf+6AZClpRoPxYnF/TsKACu3Z2fVGmI3VtIpLLsNWMa+buNPIs0hJKMUkwX5FrMARu7XUR7HRguEB8KoYnIffG86ijAc4EmHOY4nDJK0wBJ5ZzIrXVSU36yVgFa9meSuGzpPNDaXdxUp725Mo39ZHUMTQiwOu7YJrSrway0oiuerVPXx/o91gtQlF70FCfmiKGuey+YmR0iY3hOYaxBdC1QMA4lr5r0cVYrR9AeSIyWqNRvOFugQeYnxYCH+6A/GWCWKU3V8ckedmk93y/8qFKlf6qE0eIZoj6gmo=
